{"name": "test_demo2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = inc(2)", "trace": "self = <测试.test_pytest.Testadd object at 0x7f56e3696cc0>\n\n    @pytest.mark.failed\n    def test_demo2(self):\n>       assert inc(2) == 5\nE       assert 4 == 5\nE        +  where 4 = inc(2)\n\ntest_pytest.py:17: AssertionError"}, "attachments": [{"name": "stdout", "source": "c4ec812e-2bc1-4418-a4db-82d3d2b23233-attachment.txt", "type": "text/plain"}], "start": 1617092430822, "stop": 1617092430823, "uuid": "b1aafd75-5ed7-45ca-a14d-a249d346d662", "historyId": "1305f81a07d8db2896970847812e4f1a", "testCaseId": "78f3d9e0ebea22668805dfba5942c4a0", "fullName": "test_pytest.Testadd#test_demo2", "labels": [{"name": "tag", "value": "failed"}, {"name": "suite", "value": "test_pytest"}, {"name": "subSuite", "value": "Testadd"}, {"name": "host", "value": "tedu"}, {"name": "thread", "value": "35766-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest"}]}