{"name": "test_qq", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5", "trace": "self = <测试.test_biglog.Test_CLASS object at 0x7f1a9dd66198>, init_data = None\n\n    @pytest.mark.usefixtures('init_data')\n    def test_qq(self,init_data):\n        log.info('test qq ooo')\n>       assert 4 == 5\nE       assert 4 == 5\n\ntest_biglog.py:24: AssertionError"}, "start": 1617972540812, "stop": 1617972540813, "uuid": "2b3e0929-3221-4b2b-884a-5f079bb6c543", "historyId": "21a9950b23cf68de555b71c7cf9086d4", "testCaseId": "b29323cfad9d430245f81bd29daa5920", "fullName": "test_biglog.Test_CLASS#test_qq", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_data')"}, {"name": "suite", "value": "test_biglog"}, {"name": "subSuite", "value": "Test_CLASS"}, {"name": "host", "value": "tedu"}, {"name": "thread", "value": "6558-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_biglog"}]}